StudentManagementApplication/StudentManagementApp/Controllers/ClassController.cs
using Microsoft.AspNetCore.Mvc;
using StudentManagementApp.Models;
using StudentManagementApp.Repository.IRepository;
using System.Threading.Tasks;

namespace StudentManagementApp.Controllers
{
    public class ClassController : Controller
    {
        private readonly IClassRepository _classRepository;

        public ClassController(IClassRepository classRepository)
        {
            _classRepository = classRepository;
        }
        #region APIs
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _classRepository.GetAllAsync(URL.ClassAPIPath) });
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int classId)
        {
            var class1 = await _classRepository.GetAsync(URL.ClassAPIPath, classId);
            if (class1 == null)
                return Json(new { success = false, message = "Unable to delete the data" });

            await _classRepository.DeleteAsync(URL.ClassAPIPath, classId);
            return Json(new { success = true, message = "Data Deleted Successfully" });
        }
        #endregion

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> SaveOrUpdate(int? classId)
        {
            Class class1 = new Class();
            if (classId != null) 
            {
                class1 = await _classRepository.GetAsync(URL.ClassAPIPath,classId.Value);
                if (class1 == null)
                    return NotFound();
            }
            return View(class1);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveOrUpdate(Class class1) 
        {
            if (ModelState.IsValid)
            {
                //// Use the generic ExistAsync method
                //bool isDuplicate = await _classRepository.ExistAsync(URL.ClassAPIPath, class1.ClassName);

                //// Check for duplicate class name
                //if (isDuplicate && class1.ClassId == 0) // New class with duplicate name
                //{
                //    ModelState.AddModelError("", "Class with this name already exists.");
                //    return View(class1);
                //}

                if (class1.ClassId == 0) 
                    await _classRepository.CreateAsync(URL.ClassAPIPath, class1);
                else
                    await _classRepository.UpdateAsync(URL.ClassAPIPath, class1);

                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(class1);
            }
        }
    }
}

StudentManagementApplication/StudentManagementApp/Controllers/ExamController.cs
using Microsoft.AspNetCore.Mvc;
using StudentManagementApp.Models;
using StudentManagementApp.Repository.IRepository;
using System.Threading.Tasks;
using System.Linq;
using System.Collections.Generic;

namespace StudentManagementApp.Controllers
{
    public class ExamController : Controller
    {
        private readonly IExamRepository _examRepository;
        private readonly IClassRepository _classRepository;
        private readonly ISubjectRepository _subjectRepository;
        private readonly IStudentRepository _studentRepository;

        public ExamController(IExamRepository examRepository, IClassRepository classRepository, ISubjectRepository subjectRepository, IStudentRepository studentRepository)
        {
            _examRepository = examRepository;
            _classRepository = classRepository;
            _subjectRepository = subjectRepository;
            _studentRepository = studentRepository;
        }

        #region APIs
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var exams = await _examRepository.GetAllAsync(URL.ExamAPIPath);
            var classes = await _classRepository.GetAllAsync(URL.ClassAPIPath);
            var subjects = await _subjectRepository.GetAllAsync(URL.SubjectAPIPath);
            var students = await _studentRepository.GetAllAsync(URL.StudentAPIPath);

            var classDictionary = classes.ToDictionary(c => c.ClassId, c => c.ClassName);
            var subjectDictionary = subjects.ToDictionary(s => s.SubjectId, s => s.SubjectName);
            var studentDictionary = students.ToDictionary(s => s.RollNo, s => s.Name);

            var result = exams.Select(e => new
            {
                e.ExamId,
                ClassName = e.ClassId.HasValue ? classDictionary.GetValueOrDefault(e.ClassId.Value, "N/A") : "N/A",
                SubjectName = e.SubjectId.HasValue ? subjectDictionary.GetValueOrDefault(e.SubjectId.Value, "N/A") : "N/A",
                StudentName = e.RollNo != null && studentDictionary.ContainsKey(e.RollNo) ? studentDictionary[e.RollNo] : "N/A",
                e.TotalMarks,
                e.OutOfMarks
            });

            return Json(new { data = result });
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int examId)
        {
            var exam = await _examRepository.GetAsync(URL.ExamAPIPath, examId);
            if (exam == null)
                return Json(new { success = false, message = "Unable to delete the data" });

            await _examRepository.DeleteAsync(URL.ExamAPIPath, examId);
            return Json(new { success = true, message = "Data Deleted Successfully" });
        }
        #endregion

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> SaveOrUpdate(int? examId)
        {
            Exam exam = new Exam();
            if (examId != null)
            {
                exam = await _examRepository.GetAsync(URL.ExamAPIPath, examId.Value);
                if (exam == null)
                    return NotFound();
            }

            var classes = await _classRepository.GetAllAsync(URL.ClassAPIPath);
            var subjects = await _subjectRepository.GetAllAsync(URL.SubjectAPIPath);
            var students = await _studentRepository.GetAllAsync(URL.StudentAPIPath);

            ViewBag.Classes = classes ?? new List<Class>();
            ViewBag.Subjects = subjects ?? new List<Subject>();
            ViewBag.Students = students ?? new List<Student>();

            return View(exam);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveOrUpdate(Exam exam)
        {
            if (ModelState.IsValid)
            {
                if (exam.ExamId == 0)
                    await _examRepository.CreateAsync(URL.ExamAPIPath, exam);
                else
                    await _examRepository.UpdateAsync(URL.ExamAPIPath, exam);

                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewBag.Classes = await _classRepository.GetAllAsync(URL.ClassAPIPath);
                ViewBag.Subjects = await _subjectRepository.GetAllAsync(URL.SubjectAPIPath);
                ViewBag.Students = await _studentRepository.GetAllAsync(URL.StudentAPIPath);
                return View(exam);
            }
        }
    }
}

StudentManagementApplication/StudentManagementApp/Controllers/FeeController.cs
using Microsoft.AspNetCore.Mvc;
using StudentManagementApp.Models;
using StudentManagementApp.Repository.IRepository;
using System.Linq;
using System.Threading.Tasks;

namespace StudentManagementApp.Controllers
{
    public class FeeController : Controller
    {
        private readonly IFeeRepository _feeRepository;
        private readonly IClassRepository _classRepository;

        public FeeController(IFeeRepository feeRepository, IClassRepository classRepository)
        {
            _feeRepository = feeRepository;
            _classRepository = classRepository;
        }

        #region APIs
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var fees = await _feeRepository.GetAllAsync(URL.FeeAPIPath);
            var classes = await _classRepository.GetAllAsync(URL.ClassAPIPath);
            var classDictionary = classes.ToDictionary(c => c.ClassId, c => c.ClassName);

            var result = fees.Select(fee => new
            {
                FeesId = fee.FeesId,
                ClassId = fee.ClassId,
                ClassName = fee.ClassId.HasValue && classDictionary.ContainsKey(fee.ClassId.Value) ? classDictionary[fee.ClassId.Value] : "N/A",
                FeesAmount = fee.FeesAmount
            });

            return Json(new { data = result });
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int feesId)
        {
            var fee = await _feeRepository.GetAsync(URL.FeeAPIPath, feesId);
            if (fee == null)
                return Json(new { success = false, message = "Unable to delete the data" });

            await _feeRepository.DeleteAsync(URL.FeeAPIPath, feesId);
            return Json(new { success = true, message = "Data Deleted Successfully" });
        }
        #endregion

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> SaveOrUpdate(int? feesId)
        {
            Fee fee = new Fee();
            if (feesId != null)
            {
                fee = await _feeRepository.GetAsync(URL.FeeAPIPath, feesId.Value);
                if (fee == null)
                    return NotFound();
            }

            var classes = await _classRepository.GetAllAsync(URL.ClassAPIPath);
            ViewBag.Classes = classes.Select(c => new { c.ClassId, c.ClassName });

            return View(fee);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveOrUpdate(Fee fee)
        {
            if (ModelState.IsValid)
            {
                if (fee.FeesId == 0)
                    await _feeRepository.CreateAsync(URL.FeeAPIPath, fee);
                else
                    await _feeRepository.UpdateAsync(URL.FeeAPIPath, fee);

                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(fee);
            }
        }
    }
}

StudentManagementApplication/StudentManagementApp/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using StudentManagementApp.Models;
using StudentManagementApp.Repository.IRepository;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using System.IdentityModel.Tokens.Jwt;

namespace StudentManagementApp.Controllers
{
    public class UserController : Controller
    {
        private readonly IAdminRepository _adminRepository;

        public UserController(IAdminRepository adminRepository)
        {
            _adminRepository = adminRepository;
        }

        public IActionResult Register()
        {
            ViewBag.Today = DateTime.Now.ToString("yyyy-MM-dd");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(Admin admin)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var result = await _adminRepository.CreateAsync(URL.RegisterAPIPath, admin);
                    if (result)
                    {
                        return RedirectToAction("Index", "Home"); 
                    }
                    ModelState.AddModelError(string.Empty, "Failed to register admin.");
                }
                return View(admin); 
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "An error occurred while registering admin.");
                return View(admin);
            }
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginVM loginVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var userObject = await _adminRepository.Authenticate(loginVM.Email, loginVM.Password);

                    if (userObject == null)
                    {
                        ModelState.AddModelError(string.Empty, "Invalid username or password.");
                        return View(loginVM);
                    }

                    string token = null;
                    string role = null;

                    // Extract token and email from the user object
                    if (userObject is Admin admin)
                    {
                        token = admin.Token;
                    }
                    else if (userObject is Teacher teacher)
                    {
                        token = teacher.Token;
                    }
                    else
                    {
                        throw new Exception("Unknown user type.");
                    }

                    // Decode the token to extract the role
                    var jwtHandler = new JwtSecurityTokenHandler();
                    var jwtToken = jwtHandler.ReadJwtToken(token);

                    role = jwtToken.Claims.FirstOrDefault(c => c.Type == "role")?.Value;
                    if (string.IsNullOrEmpty(role))
                    {
                        throw new Exception("Role not found in token.");
                    }

                    // Continue if the token is not empty
                    if (!string.IsNullOrEmpty(token) && !string.IsNullOrEmpty(role))
                    {
                        SessionHandler.SetToken(HttpContext, token);
                        SessionHandler.SetUserRole(HttpContext, role);

                        if (SessionHandler.GetToken(HttpContext) != null &&
                            SessionHandler.GetUserRole(HttpContext) != null)
                        {
                            return RedirectToAction("Index", "Home");
                        }
                        else
                        {
                            throw new Exception("Token, email, or role is not stored in session.");
                        }
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Invalid username or password.");
                    }
                }
                return View(loginVM);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "An error occurred during authentication: " + ex.Message);
                return View(loginVM);
            }
        }



        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }
    }
}

StudentManagementApplication/StudentManagementApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@{
    var isAuthenticated = !string.IsNullOrEmpty(Context.Session.GetString("Token"));
    var userEmail = SessionHandler.GetUserEmail(Context);
    var userRole = SessionHandler.GetUserRole(Context);
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - StudentManagementApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StudentManagementApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/sidebar.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://kit.fontawesome.com/e19c476714.js">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>

</head>

<body>
    <header>
        <!-- Navbar content -->
    </header>
    <div class="container-fluid">
        <div class="row">
            <!-- Sidebar -->
            <div class="col-md-2 sidebar">
                <div class="school-logo text-center my-1">
                    <img src="https://media.istockphoto.com/id/1172148782/vector/university-campus-logo-with-text-space-for-your-slogan-tag-line.jpg?s=612x612&w=0&k=20&c=lJKl1QKcLrIGX1iZTUHxz0qaGEO-GSeUP7AV1kNcKgg=" class="img-fluid" alt="School Logo" width="100" height="100">
                    <div>
                        <p class="text-white"><i class="fas fa-map-marker-alt text-white"></i> Chandigarh, India</p>
                    </div>
                    <span class="nav-link text-white mr-3">Hii !: @userRole</span>
                </div>
                <!-- Sidebar content -->
                <ul class="nav flex-column sidebar-nav">
                    @if (isAuthenticated && userRole == "Admin")
                    {
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Class" asp-action="Index"><i class="fas fa-chalkboard-teacher"></i> Class</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Subject" asp-action="Index"><i class="fas fa-book-open"></i> Subject</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Teacher" asp-action="Index"><i class="fas fa-user-tie"></i> Teachers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="TeacherSubject" asp-action="Index"><i class="fas fa-list-alt"></i> Teacher Subjects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="TeacherAttendance" asp-action="Index"><i class="fas fa-calendar-check"></i> Teacher Attendance</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Expense" asp-action="Index"><i class="fas fa-receipt"></i> Expense</a>
                        </li>
                    }
                    else if (isAuthenticated && userRole == "Teacher")
                    {

                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Student" asp-action="Index"><i class="fas fa-user-graduate"></i> Student</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="StudentAttendance" asp-action="Index"><i class="fas fa-calendar-check"></i> Student Attendance</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Fee" asp-action="Index"><i class="fas fa-dollar-sign"></i> Fee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Exam" asp-action="Index"><i class="fas fa-pencil-alt"></i> Exam</a>
                        </li>

                    }
                    <!-- Navigation links -->
                  
                </ul>
                <ul class="navbar-nav mt-auto">
                    @if (isAuthenticated)
                    {
                       
                        
                        <form asp-area="" asp-controller="User" asp-action="Logout" method="post" class="form-inline">
                            <button type="submit" class="nav-link btn btn-danger text-white"><i class="fas fa-sign-out-alt"></i> Logout</button>
                        </form>
                        @if (isAuthenticated && userRole == "Admin")
                        {
                            <div>
                                <a class="btn btn-yellow text-dark" asp-area="" asp-controller="User" asp-action="Register"><i class="fas fa-user-plus"></i> Register</a>
                            </div>
                            <br>
                        }
                        else if (User.IsInRole("Teacher"))
                        {
                            <!-- Render Teacher-specific content here -->
                        }
                    }
                    else
                    {
                        <div>
                            <a class="btn btn-yellow text-dark" asp-area="" asp-controller="User" asp-action="Register"><i class="fas fa-user-plus"></i> Register</a>
                        </div>
                        <br>
                        <div>
                            <a class="btn btn-primary text-white" asp-area="" asp-controller="User" asp-action="Login"><i class="fas fa-sign-in-alt"></i> Login</a>
                        </div>
                    }
                </ul>

            </div>
            <!-- Main content -->
            <div class="col-md-10 offset-md-2 main-content">
                <header>
                    <h1 class="school-name text-center">Carmel Convent School</h1>
                </header>
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>
    @*
    <footer class="border-top footer text-muted">
    <div class="container">
    &copy; 2024 - StudentManagementApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>